- name: Installation de vim
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes
  
    - name: Installer le paquet vim
      apt:
        name: "vim"
        state: present

    - name: check /etc/password
      ansible.builtin.file:
        path: /etc/passwd
        state: file
