- name: Installation de vim
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes
  
    - name: Installer les paquets
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server
      register: install_packages

    - name : debug variables
      ansible.builtin.debug:
        var: install_packages

    - name: change file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: 'Bonjour depuis Ansible'
      when: install_packages.changed == false

    - name: start service
      ansible.builtin.service:
        name: apache2
        state: started
      when: install_packages.changed == false
