- name: Installation de role
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: install role geerlingguy.docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_edition: 'ce'
